version: '3'

networks:
  default:
    external:
      name: hr-saas

services:
  user-web:
    build:
      context: ./user-web
    environment:
      DEBUG: "true"
      GIN_MODE: "debug"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${USER_NACOS_DATA_ID}"
      NACOS_GROUP: "${USER_NACOS_GROUP}"
      NACOS_NAMESPACE: "${USER_NACOS_NAMESPACE}"
    volumes:
      - ./user-web/config-debug.yml:/app/config-debug.yml

  company-web:
    build:
      context: ./company-web
    environment:
      DEBUG: "true"
      GIN_MODE: "release"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${COMPANY_NACOS_DATA_ID}"
      NACOS_GROUP: "${COMPANY_NACOS_GROUP}"
      NACOS_NAMESPACE: "${COMPANY_NACOS_NAMESPACE}"
