version: '3'

networks:
  default:
    external:
      name: ${NETWORK_NAME}

services:
  user-web:
    build:
      context: ./user-web
    environment:
      DEBUG: "true"
      GIN_MODE: "debug"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${USER_NACOS_DATA_ID}"
      NACOS_GROUP: "${USER_NACOS_GROUP}"
      NACOS_NAMESPACE: "${USER_NACOS_NAMESPACE}"
    volumes:
      - ./user-web/config-debug.yml:/app/config-debug.yml

  company-web:
    build:
      context: ./company-web
    environment:
      DEBUG: "true"
      GIN_MODE: "debug"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${COMPANY_NACOS_DATA_ID}"
      NACOS_GROUP: "${COMPANY_NACOS_GROUP}"
      NACOS_NAMESPACE: "${COMPANY_NACOS_NAMESPACE}"
    volumes:
      - ./company-web/config-debug.yml:/app/config-debug.yml

  upload-web:
    build:
      context: ./upload-web
    environment:
      DEBUG: "true"
      GIN_MODE: "debug"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${UPLOAD_NACOS_DATA_ID}"
      NACOS_GROUP: "${UPLOAD_NACOS_GROUP}"
      NACOS_NAMESPACE: "${UPLOAD_NACOS_NAMESPACE}"
    volumes:
      - ./upload-web/config-debug.yml:/app/config-debug.yml

  resume-web:
    build:
      context: ./resume-web
    environment:
      DEBUG: "true"
      GIN_MODE: "debug"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${RESUME_NACOS_DATA_ID}"
      NACOS_GROUP: "${RESUME_NACOS_GROUP}"
      NACOS_NAMESPACE: "${RESUME_NACOS_NAMESPACE}"
    volumes:
      - ./resume-web/config-debug.yml:/app/config-debug.yml

  message-web:
    build:
      context: ./message-web
    environment:
      DEBUG: "true"
      GIN_MODE: "debug"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${MESSAGE_NACOS_DATA_ID}"
      NACOS_GROUP: "${MESSAGE_NACOS_GROUP}"
      NACOS_NAMESPACE: "${MESSAGE_NACOS_NAMESPACE}"
    volumes:
      - ./message-web/config-debug.yml:/app/config-debug.yml

  recruit-web:
    build:
      context: ./recruit-web
    environment:
      DEBUG: "true"
      GIN_MODE: "debug"
      NACOS_HOST: "${NACOS_HOST}"
      NACOS_PORT: "${NACOS_PORT}"
      NACOS_USERNAME: "${NACOS_USERNAME}"
      NACOS_PASSWORD: "${NACOS_PASSWORD}"
      NACOS_DATA_ID: "${RECRUIT_NACOS_DATA_ID}"
      NACOS_GROUP: "${RECRUIT_NACOS_GROUP}"
      NACOS_NAMESPACE: "${RECRUIT_NACOS_NAMESPACE}"
    volumes:
      - ./recruit-web/config-debug.yml:/app/config-debug.yml