// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: counter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResumeCounterServiceClient is the client API for ResumeCounterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResumeCounterServiceClient interface {
	// 统计简历
	CountResume(ctx context.Context, in *CountResumeRequest, opts ...grpc.CallOption) (*CountResumeResponse, error)
}

type resumeCounterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResumeCounterServiceClient(cc grpc.ClientConnInterface) ResumeCounterServiceClient {
	return &resumeCounterServiceClient{cc}
}

func (c *resumeCounterServiceClient) CountResume(ctx context.Context, in *CountResumeRequest, opts ...grpc.CallOption) (*CountResumeResponse, error) {
	out := new(CountResumeResponse)
	err := c.cc.Invoke(ctx, "/ResumeCounterService/CountResume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResumeCounterServiceServer is the server API for ResumeCounterService service.
// All implementations must embed UnimplementedResumeCounterServiceServer
// for forward compatibility
type ResumeCounterServiceServer interface {
	// 统计简历
	CountResume(context.Context, *CountResumeRequest) (*CountResumeResponse, error)
	mustEmbedUnimplementedResumeCounterServiceServer()
}

// UnimplementedResumeCounterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResumeCounterServiceServer struct {
}

func (UnimplementedResumeCounterServiceServer) CountResume(context.Context, *CountResumeRequest) (*CountResumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountResume not implemented")
}
func (UnimplementedResumeCounterServiceServer) mustEmbedUnimplementedResumeCounterServiceServer() {}

// UnsafeResumeCounterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResumeCounterServiceServer will
// result in compilation errors.
type UnsafeResumeCounterServiceServer interface {
	mustEmbedUnimplementedResumeCounterServiceServer()
}

func RegisterResumeCounterServiceServer(s grpc.ServiceRegistrar, srv ResumeCounterServiceServer) {
	s.RegisterService(&ResumeCounterService_ServiceDesc, srv)
}

func _ResumeCounterService_CountResume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountResumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResumeCounterServiceServer).CountResume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ResumeCounterService/CountResume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResumeCounterServiceServer).CountResume(ctx, req.(*CountResumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResumeCounterService_ServiceDesc is the grpc.ServiceDesc for ResumeCounterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResumeCounterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ResumeCounterService",
	HandlerType: (*ResumeCounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CountResume",
			Handler:    _ResumeCounterService_CountResume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "counter.proto",
}
